{% set name = "ipyfilebrowser" %}
{% set version = "0.1.2" %}

package:
    name: "{{ name|lower }}"
    version: "{{ version }}"

source:
    url: "https://github.com/mbonix/{{ name }}/archive/{{ version }}.tar.gz"
    sha256: 4a5940e66c1fc5f44f3dbda5caf5fd8100bf79933c8ba2075b1ad7d74ae9473d


build:
    noarch: python
    number: 0
    script: "{{ PYTHON }} -m pip install . -vv"

requirements:
    host:
        - pip
        - python
    run:
        - ipywidgets
        - python

test:
    imports:
        - ipyfilebrowser

about:
    home: https://github.com/mbonix/blpd
    license: MIT
    license_file: LICENSE
    summary: "A file browser widget for Jupyter / Jupyterlab based on ipywidgets.VBox"

extra:
    maintainers:
        - mbonix
